#!/usr/bin/env node
/**
 * Write `dist/sw.js`, stamped with a version that changes when the build does.
 *
 * ## Why there is a service worker at all
 *
 * The game ships a web-app manifest and is installable, and until now an
 * installed copy with no connection showed the browser's own error page — for a
 * game that is entirely client-side after boot. A career in progress lives in
 * `localStorage`; the only thing standing between a player on the underground
 * and the rest of their season was the twenty seconds of network it takes to
 * fetch a bundle that never changes.
 *
 * ## Why it is hand-written, and what it precaches
 *
 * A full precache manifest is the usual answer and it is the wrong one here:
 * listing two hundred crests means an install that fails as a unit if any one
 * of them 404s, for art the app already has a generated fallback for. So the
 * crests, trophies, icons and fonts are cached as they are asked for, and one
 * that never loads simply never gets cached.
 *
 * But the **shell** has to be precached, and the first version of this file
 * learned that the hard way. A service worker does not control the page that
 * registered it, so nothing about the first visit goes through the worker: the
 * document and the bundle were already in flight before it existed. Cache only
 * what passes through and the cache is empty exactly when it matters — the
 * offline check reloaded and got `ERR_FAILED`, because there was no HTML to
 * fall back to and no bundle to boot if there had been.
 *
 * So the install step fetches the four or five files a boot cannot do without:
 * the document, its entry script and stylesheet, and both language packs. Both,
 * because the pack is a dynamic import and an offline player who switches
 * language should not hit a wall. That list is generated below from what the
 * build actually produced rather than written by hand, so it cannot drift.
 *
 * ## The rule that matters
 *
 * **HTML is network-first, everything else is cache-first.** A service worker
 * that serves cached HTML pins the player to an old build — they reload, get
 * the same broken page, and there is nothing they can do about it. Assets are
 * safe to pin because their names contain their content hash: a new build asks
 * for different filenames.
 *
 * Runs after `vite build`, alongside `prerender.mjs` and `build-pages.mjs`.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, '..', 'dist');

/**
 * The version, from the built asset names.
 *
 * Their filenames contain their own content hashes, so this changes exactly
 * when something in the bundle changes — and stays the same across a rebuild of
 * identical source, which keeps a redeploy from throwing away every player's
 * warm cache for nothing.
 */
const built = readdirSync(join(dist, 'assets')).sort();
const version = createHash('sha256').update(built.join('|')).digest('hex').slice(0, 12);

/**
 * The shell: everything a cold boot needs before the app can draw anything.
 *
 * Matched by shape rather than named, because the hashes change every build.
 * `index-*.js` is the entry, `index-*.css` the stylesheet, and `en-*.js` /
 * `zh-*.js` the two language packs. `clubs-zh-*.js` is left out — it is a
 * second-order chunk the Chinese build fetches after it has already drawn.
 */
const SHELL_PATTERNS = [/^index-.*\.js$/, /^index-.*\.css$/, /^en-.*\.js$/, /^zh-.*\.js$/];

/*
 * Checked per pattern, not by counting matches.
 *
 * The first version compared one total against the number of patterns, which
 * passes on the wrong set: two files matching `index-*.js` and none matching
 * `zh-*.js` still totals four. That ships a precache with no Chinese language
 * pack, and the failure lands on a Chinese-speaking player offline — which no
 * gate plays, because the offline check runs in English on a phone.
 */
const shell = ['/'];
const unmatched = [];
for (const pattern of SHELL_PATTERNS) {
  const hits = built.filter((name) => pattern.test(name));
  if (hits.length === 0) unmatched.push(String(pattern));
  for (const name of hits) shell.push(`/assets/${name}`);
}
if (unmatched.length > 0) {
  console.error(`build-sw: no built asset matches ${unmatched.length} shell pattern(s):`);
  console.error(`  ${unmatched.join('\n  ')}`);
  console.error(`  What the build produced: ${built.join(', ')}`);
  console.error('  The asset names changed. Fix SHELL_PATTERNS — an incomplete');
  console.error('  shell is an offline boot that white-screens, and for one');
  console.error('  language only if the missing pattern is a locale pack.');
  process.exit(1);
}

const sw = `/*
 * Decision FC — offline shell. Generated by scripts/build-sw.mjs; do not edit
 * in dist. Version is a hash of the built asset names.
 */
const VERSION = '${version}';
const CACHE = 'dfc-' + VERSION;

/* The shell, generated from this build's own output. */
const SHELL = ${JSON.stringify(shell)};

/*
 * What is safe to keep forever: anything whose filename contains its own
 * content hash, plus the static art, which is replaced by a different file
 * rather than edited in place.
 */
const CACHEABLE = /^\\/(assets|fonts|crests|trophies|icons)\\//;

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // Individually, not addAll: one missing file must not throw away the
      // other four. An install that half-works still boots offline; one that
      // rejects leaves the player with nothing.
      await Promise.all(
        SHELL.map((path) =>
          fetch(path, { cache: 'reload' })
            .then((response) => (response.ok ? cache.put(path, response) : undefined))
            .catch(() => {}),
        ),
      );
      // Take over at once. A worker that waits for every tab to close is a
      // worker that never activates for somebody who keeps the game open.
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // ---- HTML: network first ------------------------------------------------
  // Never pin a document. A cached page that boots an asset the new build no
  // longer has is a white screen the player cannot reload their way out of.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          const fresh = await fetch(request);
          const cache = await caches.open(CACHE);
          cache.put(request, fresh.clone());
          return fresh;
        } catch {
          // Offline. The last copy of this page, or the last copy of any page.
          const cache = await caches.open(CACHE);
          // This exact page, then the shell. The Chinese twin and the content
          // pages fall back to the game itself rather than to nothing, which is
          // the right answer for a player who is offline and wanted to play.
          // (No backticks in this file below the template opener: it is a
          // template literal, and one would end it.)
          return (await cache.match(request)) ?? (await cache.match('/')) ?? Response.error();
        }
      })(),
    );
    return;
  }

  // ---- hashed assets: cache first ----------------------------------------
  if (!CACHEABLE.test(url.pathname)) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(request);
      if (hit) return hit;
      const response = await fetch(request);
      // Only a real answer is worth keeping. A 404 crest has a generated badge
      // waiting for it in the app and must not be cached as the answer.
      if (response.ok) cache.put(request, response.clone());
      return response;
    })(),
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
// Sanity: the bundle the worker is versioned against has to exist.
const entry = readdirSync(join(dist, 'assets')).find((name) => /^index-.*\.js$/.test(name));
if (!entry) {
  console.error('build-sw: no index-*.js in dist/assets — did vite build run?');
  process.exit(1);
}
console.log(`wrote dist/sw.js (version ${version}, ${readFileSync(join(dist, 'sw.js')).length} bytes)`);
