/**
 * How much of a career is the player's doing?
 *
 * "It is a luck game" is the easiest thing to say about a choice simulator, and
 * the hardest to argue with, because the usual evidence — a balance sweep — is
 * generated by *random* play and therefore cannot tell the two apart. This tool
 * separates them by construction:
 *
 *   **Luck** is how much careers differ from each other when the decisions are
 *   made the same way. Same policy, different seeds.
 *
 *   **Choice** is how much one career differs from itself when the decisions
 *   are made differently. Same seed, different policies.
 *
 * Both are measured on the same scale — the leaderboard numbers the game
 * actually ranks on — so they can be compared directly. If the controllable
 * range on a single seed is a serious fraction of the spread across seeds, the
 * player's decisions are worth more than the roll of the dice.
 *
 * Five policies, chosen to span what a real player might do rather than to
 * flatter the engine: chase the biggest club, go as high as you can still play,
 * stay loyal, refuse every step up, and pick at random.
 *
 * Usage: pnpm skill [--runs=400] [--pace=standard] [--assert]
 */

import { WORLD } from '../packages/content/src/index.js';
import {
  createCareer,
  decide,
  mulberry32,
  selectIdentity,
  PLAYABLE_POSITIONS,
  type Pace,
  type Position,
} from '../packages/engine/src/index.js';
import { COUNTRIES } from '../packages/content/src/data/countries.js';
import { POLICIES, type Policy } from './policies';

const arg = (name: string) => process.argv.find((a) => a.startsWith(`--${name}=`))?.split('=')[1];
const PACE = (arg('pace') ?? 'standard') as Pace;
const ASSERT = process.argv.includes('--assert');
/**
 * A gate needs a sample its own thresholds can survive.
 *
 * 400 seeds puts a standard error of about 2.5 points on a win rate near 65%,
 * and the floor below is 60 — close enough that the same build passed and
 * failed on consecutive runs. Reading it by eye is cheap at 400; asserting on
 * it is not.
 */
const RUNS = Number(arg('runs') ?? (ASSERT ? 1600 : 400));

interface Outcome {
  legacy: number;
  earnings: number;
  peakValue: number;
  peakOverall: number;
}

/**
 * One career. The seed fixes everything the player does not control — the
 * identity, the deck, every roll — so two policies on the same index differ
 * only in the decisions taken.
 */
function play(index: number, policy: Policy): Outcome | null {
  const setup = mulberry32(index * 2654435761);
  const country = COUNTRIES[Math.floor(setup() * COUNTRIES.length)]!;
  let state = selectIdentity(
    createCareer(`skill-${index}`, PACE),
    {
      lastName: 'Test',
      shirtNumber: 9,
      foot: setup() < 0.25 ? 'left' : 'right',
      countryId: country.id,
      position: PLAYABLE_POSITIONS[Math.floor(setup() * PLAYABLE_POSITIONS.length)] as Position,
      archetype: (['pace', 'technical', 'physical'] as const)[Math.floor(setup() * 3)]!,
    },
    WORLD,
  );

  // A separate stream for the policy, so a policy that consults it does not
  // shift the identity the seed already fixed.
  const choices = mulberry32(index * 40503 + 11);
  let guard = 0;
  while (state.pending && guard < 600) {
    state = decide(state, policy(state, choices), WORLD);
    guard += 1;
  }
  if (state.phase !== 'summary' || !state.retirement) return null;
  return {
    legacy: state.retirement.legacyScore,
    earnings: state.totals.grossEarnings,
    peakValue: state.totals.peakMarketValue,
    peakOverall: state.totals.peakOverall,
  };
}

const median = (values: number[]): number => {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)]!;
};
const quantile = (values: number[], q: number): number => {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))]!;
};

const results = new Map<string, Outcome[]>();
/** Per seed: how far apart the best and worst policy landed on it. */
const perSeedRange: number[] = [];

for (let i = 0; i < RUNS; i += 1) {
  const onThisSeed: number[] = [];
  for (const { name, play: policy } of POLICIES) {
    const outcome = play(i, policy);
    if (!outcome) continue;
    if (!results.has(name)) results.set(name, []);
    results.get(name)!.push(outcome);
    onThisSeed.push(outcome.legacy);
  }
  if (onThisSeed.length === POLICIES.length) {
    perSeedRange.push(Math.max(...onThisSeed) - Math.min(...onThisSeed));
  }
}

const money = (v: number) => (v >= 1e6 ? `€${(v / 1e6).toFixed(1)}M` : `€${(v / 1e3).toFixed(0)}K`);

console.log(`\n  ${RUNS} seeds · pace=${PACE} · ${POLICIES.length} policies each\n`);
console.log('  WHAT EACH WAY OF PLAYING PRODUCES (medians)');
console.log('    policy        legacy   earnings   peak value   peak OVR');
for (const { name } of POLICIES) {
  const rows = results.get(name) ?? [];
  console.log(
    `    ${name.padEnd(13)} ${String(median(rows.map((r) => r.legacy))).padStart(6)}` +
      `   ${money(median(rows.map((r) => r.earnings))).padStart(8)}` +
      `   ${money(median(rows.map((r) => r.peakValue))).padStart(10)}` +
      `   ${String(median(rows.map((r) => r.peakOverall))).padStart(8)}`,
  );
}

// The two numbers the whole tool exists for.
const ambitious = (results.get('ambitious') ?? []).map((r) => r.legacy);
const unambitious = (results.get('unambitious') ?? []).map((r) => r.legacy);
const randomPlay = (results.get('random') ?? []).map((r) => r.legacy);

// Luck: how far apart two careers land when played the same way.
const luckSpread = quantile(ambitious, 0.9) - quantile(ambitious, 0.1);
// Choice: how far apart one career lands when played differently.
const choiceSpread = median(perSeedRange);
const skillShare = choiceSpread / (choiceSpread + luckSpread);

console.log('\n  LUCK versus CHOICE, on the legacy score');
console.log(`    same policy, different seeds  (p10→p90)   ${luckSpread}`);
console.log(`    same seed, different policies (median)    ${choiceSpread}`);
console.log(
  `    → the player controls ${(skillShare * 100).toFixed(0)}% of the range he can see`,
);

/**
 * Deliberate play, not one particular idea of it.
 *
 * This measured `ambitious` alone — chase the biggest badge on the card — and
 * that stopped being the best way to play the game. `shrewd` reads the squad
 * role against the player's own ability, which is the decision the whole ladder
 * was built to pose, and it now tops the legacy board. Holding the gate to
 * `ambitious` would have it fail precisely when the game got deeper: badge
 * chasing losing to role reading is the design working.
 *
 * So the claim under test is the honest one — **playing deliberately beats
 * playing indifferently** — and it is measured on whichever deliberate policy
 * the game currently rewards, seed by seed against the same career played
 * badly and played at random.
 */
const DELIBERATE = ['ambitious', 'shrewd'] as const;
const best = DELIBERATE.map((name) => (results.get(name) ?? []).map((r) => r.legacy)).reduce((a, b) =>
  median(a) >= median(b) ? a : b,
);
const bestName = DELIBERATE.map((name) => ({ name, list: (results.get(name) ?? []).map((r) => r.legacy) })).reduce(
  (a, b) => (median(a.list) >= median(b.list) ? a : b),
).name;

let beatsRandom = 0;
let beatsFloor = 0;
const n = Math.min(best.length, randomPlay.length, unambitious.length);
for (let i = 0; i < n; i += 1) {
  if (best[i]! > randomPlay[i]!) beatsRandom += 1;
  if (best[i]! > unambitious[i]!) beatsFloor += 1;
}
console.log('\n  DOES PLAYING WELL WIN?');
console.log(`    best deliberate policy is ${bestName}`);
console.log(`    it beats random      on ${((beatsRandom / n) * 100).toFixed(0)}% of seeds`);
console.log(`    it beats unambitious on ${((beatsFloor / n) * 100).toFixed(0)}% of seeds`);
console.log(
  `    median legacy: ${bestName} ${median(best)} · ambitious ${median(ambitious)} · random ${median(randomPlay)} · unambitious ${median(unambitious)}`,
);

/**
 * Different routes, not one route. The design claim is that the three boards
 * reward different decisions — so a policy that maximises one should not
 * automatically top the others.
 */
console.log('\n  DO THE THREE BOARDS REWARD DIFFERENT PLAY?');
for (const board of ['legacy'] as const) {
  const ranking = POLICIES.map(({ name }) => ({
    name,
    value: median((results.get(name) ?? []).map((r) => r[board])),
  })).sort((a, b) => b.value - a.value);
  console.log(`    ${board} medians  ${ranking.map((r) => `${r.name} ${r.value}`).join(' · ')}`);
}
for (const board of ['legacy', 'earnings', 'peakValue'] as const) {
  const ranking = POLICIES.map(({ name }) => ({
    name,
    value: median((results.get(name) ?? []).map((r) => r[board])),
  })).sort((a, b) => b.value - a.value);
  console.log(`    ${board.padEnd(10)} ${ranking.map((r) => r.name).join(' > ')}`);
}
console.log('');

if (ASSERT) {
  const failures: string[] = [];
  /*
   * The floors sit a little under what the game currently does — 66% / 65% /
   * 31% over 1,600 seeds — so this catches a change that quietly hands the
   * career to the dice without flaking on ordinary sampling noise. They are not
   * aspirations: if the game should reward decisions *more* than it does, raise
   * the design first and these afterwards.
   *
   * The floor against `unambitious` was 65 and is now 60, and the reason is a
   * design decision rather than a drift. Cards no longer deal an option that
   * another option beats on stature, role and wage alike — see `outbids` — so
   * indifferent play can no longer be punished for pressing a button that was
   * dead on arrival. That lifted the floor by ten per cent of a career
   * (unambitious 1,627 → 1,785 legacy) while leaving deliberate play where it
   * was, and it compresses this particular statistic by construction.
   *
   * **These numbers are the 2026-08 reference and have moved since.** The run
   * that shipped on 2026-09-17 prints 69% / 63% / 29%: the medal-and-minutes
   * change lowered every legacy score, which compressed `skillShare` from 31%
   * to 29%. The floors below were deliberately left where they were rather
   * than lowered to follow it — a floor that chases the measurement is not a
   * floor — and 29% against a 22% floor is still comfortable.
   */
  if (beatsFloor / n < 0.6) {
    failures.push(
      `deliberate play beat unambitious on only ${((beatsFloor / n) * 100).toFixed(0)}% of seeds (want ≥60%)`,
    );
  }
  if (beatsRandom / n < 0.58) {
    failures.push(
      `deliberate play beat random on only ${((beatsRandom / n) * 100).toFixed(0)}% of seeds (want ≥58%)`,
    );
  }
  if (skillShare < 0.22) {
    failures.push(
      `choice accounts for only ${(skillShare * 100).toFixed(0)}% of the visible range (want ≥22%)`,
    );
  }

  /**
   * **Reading a squad role must beat chasing a badge.**
   *
   * This is the assertion that was missing, and its absence was the most
   * valuable thing an independent audit of the September work found. Over 400
   * seeds the best way to play this game used to be `ambitious` — take the
   * biggest club on every card and ignore the role that comes with it — which
   * made the squad ladder the whole game is built on decoration. Fixing it
   * (a medal is worth the minutes behind it; a bench costs development) was
   * the deepest change in that round.
   *
   * And nothing guarded the result. The three floors above all use *the best*
   * deliberate policy, so they stay green whichever of the two is winning: a
   * future tuning pass could quietly restore the inversion with every gate
   * passing and the docs still claiming otherwise.
   *
   * Legacy is the board that has to hold, because it is the one the ordering
   * is a claim about. The margin is small by nature — 1,986 against 1,939 when
   * this was written, about 2.4% — so this asserts the *order* and not a gap:
   * a tie or a reversal fails, and the width of the win is a design question
   * rather than a gate.
   */
  const shrewdLegacy = median((results.get('shrewd') ?? []).map((r) => r.legacy));
  const ambitiousLegacy = median(ambitious);
  if (shrewdLegacy <= ambitiousLegacy) {
    failures.push(
      `chasing the badge beats reading the role again: ambitious ${ambitiousLegacy} ≥ shrewd ${shrewdLegacy} on legacy`,
    );
  }
  if (failures.length > 0) {
    console.log('  ✗ this is drifting towards a luck game:');
    for (const f of failures) console.log(`      ${f}`);
    console.log('');
    process.exit(1);
  }
  console.log('  ✓ decisions still decide careers\n');
}
